#!/usr/bin/env python3
"""Build the deterministic storefront widget bundle from authoritative modules."""
from __future__ import annotations

import argparse
import hashlib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MODULE_DIR = ROOT / 'assets' / 'js' / 'widget'
ORDER_FILE = MODULE_DIR / 'build-order.txt'
TARGET = ROOT / 'assets' / 'js' / 'widget.js'


def module_names() -> list[str]:
    names: list[str] = []
    for raw in ORDER_FILE.read_text(encoding='utf-8').splitlines():
        name = raw.strip()
        if not name or name.startswith('#'):
            continue
        if Path(name).name != name or not name.endswith('.js'):
            raise RuntimeError(f'Invalid widget module name: {name!r}')
        names.append(name)
    if not names or len(names) != len(set(names)):
        raise RuntimeError('Widget build order is empty or contains duplicates.')
    return names


def normalized(path: Path) -> str:
    text = path.read_text(encoding='utf-8').replace('\r\n', '\n').replace('\r', '\n')
    return text.rstrip('\n') + '\n'


def build() -> bytes:
    names = module_names()
    parts = []
    digest = hashlib.sha256()
    for name in names:
        path = MODULE_DIR / name
        if not path.is_file():
            raise RuntimeError(f'Missing widget module: {name}')
        content = normalized(path)
        digest.update(name.encode('utf-8'))
        digest.update(b'\0')
        digest.update(content.encode('utf-8'))
        parts.append(content.rstrip('\n'))
    header = (
        '/* Generated by scripts/build-widget.py from assets/js/widget/build-order.txt.\n'
        ' * Authoritative source SHA-256: ' + digest.hexdigest() + '\n'
        ' * Do not edit this bundle directly.\n'
        ' */\n\n'
    )
    return (header + '\n\n'.join(parts) + '\n').encode('utf-8')


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    output = build()
    if args.check:
        current = TARGET.read_bytes() if TARGET.is_file() else b''
        if current != output:
            raise SystemExit('assets/js/widget.js is not the exact deterministic output of its modules.')
        print('Widget bundle is current.')
        return
    TARGET.write_bytes(output)
    print(f'Wrote {TARGET.relative_to(ROOT)} ({len(output)} bytes).')


if __name__ == '__main__':
    main()
